In [2]:
import numpy as np

#  Inicializar Arrays
a = np.array([1, 2, 3])   # Crea un array de rango 1
print(type(a), a.shape, a[0], a[1], a[2])
print (a)

<class 'numpy.ndarray'> (3,) 1 2 3
[1 2 3]


In [3]:
a = np.zeros((2,2))   # Crea un array de 2x2 de ceros
print(type(a), a.shape, a[0, 0], a[0, 1], a[1, 0], a[1, 1])
print (a)

<class 'numpy.ndarray'> (2, 2) 0.0 0.0 0.0 0.0
[[0. 0.]
 [0. 0.]]


In [12]:
a = np.ones((3,2,3,2))    # Crea un array de 1x2 de unos
print(type(a), a.shape)
print (a)
print (a.size) #cantidad de valores
print (a.ndim) #cantidad de dimensiones


<class 'numpy.ndarray'> (3, 2, 3, 2)
[[[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]]
36
4


In [16]:
a = np.arange(0, 10, 2, dtype=np.uint8)   # Crea un array de 0 a 10 con saltos de 2

[0 2 4 6 8]


In [17]:
a # todos los valores de a son enteros sin signo de 8 bits

array([0, 2, 4, 6, 8], dtype=uint8)

In [48]:
def slow(n=10000):
    x = np.linspace(-1, 1, n)
    y = np.linspace(-1, 1, n)
    z = np.empty((n, n))

    #print ("y, size:", y.size, "--- shape:", y.shape)
    #print ("x, size:", x.size, "--- shape:", x.shape)
    #print ("z, size:", z.size, "--- shape:", z.shape, "\n")

    for i, _y in enumerate(y):
        for j, _x in enumerate(x):
            z[i, j] = np.sqrt(_x**2 + _y**2)
            #print ("i: ", i, " _y: ", round(_y,2), " j: ", j, " _x: ", round(_x,2), " z[i, j]: ", round(z[i, j],2))
    return x, y, z
%time x, y, z = slow()



CPU times: total: 1min 36s
Wall time: 1min 46s


In [49]:
def rapido(n=10000):
    p = np.linspace(-1, 1, n)
    x, y = np.meshgrid(p, p)
    z = np.sqrt(x**2 + y**2)
    return x, y, z
    
%time x, y, z = rapido()

CPU times: total: 875 ms
Wall time: 981 ms


In [58]:
x = np.linspace(-100,100)
print (x)
print (x.size)

[-100.          -95.91836735  -91.83673469  -87.75510204  -83.67346939
  -79.59183673  -75.51020408  -71.42857143  -67.34693878  -63.26530612
  -59.18367347  -55.10204082  -51.02040816  -46.93877551  -42.85714286
  -38.7755102   -34.69387755  -30.6122449   -26.53061224  -22.44897959
  -18.36734694  -14.28571429  -10.20408163   -6.12244898   -2.04081633
    2.04081633    6.12244898   10.20408163   14.28571429   18.36734694
   22.44897959   26.53061224   30.6122449    34.69387755   38.7755102
   42.85714286   46.93877551   51.02040816   55.10204082   59.18367347
   63.26530612   67.34693878   71.42857143   75.51020408   79.59183673
   83.67346939   87.75510204   91.83673469   95.91836735  100.        ]
50
